server:
  port: 8080

spring:
  # 아래 코드를 추가해서 secret 파일을 포함시킵니다.
  profiles:
    include: secret

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    # url, username, password는 secret 파일에 있으니 여기선 지웁니다!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect